version: '3'

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: propertymap
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: